import typing
from System import Attribute

class UsesLuminPlatformLevelAttribute(Attribute):
    def __init__(self, platformLevel: int) -> None: ...
    @property
    def platformLevel(self) -> int: ...
    @property
    def TypeId(self) -> typing.Any: ...


class UsesLuminPrivilegeAttribute(Attribute):
    def __init__(self, privilege: str) -> None: ...
    @property
    def privilege(self) -> str: ...
    @property
    def TypeId(self) -> typing.Any: ...

