import typing

class FrameCapture:
    @staticmethod
    def BeginCaptureToFile(path: str) -> None: ...
    @staticmethod
    def BeginCaptureToXcode() -> None: ...
    @staticmethod
    def CaptureNextFrameToFile(path: str) -> None: ...
    @staticmethod
    def CaptureNextFrameToXcode() -> None: ...
    @staticmethod
    def EndCapture() -> None: ...
    @staticmethod
    def IsDestinationSupported(dest: FrameCaptureDestination) -> bool: ...


class FrameCaptureDestination(typing.SupportsInt):
    @typing.overload
    def __init__(self, value : int) -> None: ...
    @typing.overload
    def __init__(self, value : int, force_if_true: bool) -> None: ...
    def __int__(self) -> int: ...
    
    # Values:
    DevTools : FrameCaptureDestination # 1
    GPUTraceDocument : FrameCaptureDestination # 2

