from UnityEditor import BuildTargetGroup
from System import Array_1

class VREditor:
    def __init__(self) -> None: ...
    @staticmethod
    def GetVREnabledOnTargetGroup(targetGroup: BuildTargetGroup) -> bool: ...
    @staticmethod
    def NativeSetVREnabledDevicesOnTargetGroup(targetGroup: BuildTargetGroup, devices: Array_1[str]) -> None: ...
    @staticmethod
    def SetVREnabledDevicesOnTargetGroup(targetGroup: BuildTargetGroup, devices: Array_1[str]) -> None: ...
    @staticmethod
    def SetVREnabledOnTargetGroup(targetGroup: BuildTargetGroup, value: bool) -> None: ...

