import typing, abc
from UnityEngine.UIElements import VisualElement
from UnityEditor.PackageManager import PackageInfo
from System.Collections.Generic import IEnumerable_1

class IPackageManagerExtension(typing.Protocol):
    @abc.abstractmethod
    def CreateExtensionUI(self) -> VisualElement: ...
    @abc.abstractmethod
    def OnPackageAddedOrUpdated(self, packageInfo: PackageInfo) -> None: ...
    @abc.abstractmethod
    def OnPackageRemoved(self, packageInfo: PackageInfo) -> None: ...
    @abc.abstractmethod
    def OnPackageSelectionChange(self, packageInfo: PackageInfo) -> None: ...


class PackageManagerExtensions(abc.ABC):
    @staticmethod
    def RegisterExtension(extension: IPackageManagerExtension) -> None: ...


class Sample:
    @property
    def description(self) -> str: ...
    @description.setter
    def description(self, value: str) -> str: ...
    @property
    def displayName(self) -> str: ...
    @displayName.setter
    def displayName(self, value: str) -> str: ...
    @property
    def importPath(self) -> str: ...
    @importPath.setter
    def importPath(self, value: str) -> str: ...
    @property
    def interactiveImport(self) -> bool: ...
    @interactiveImport.setter
    def interactiveImport(self, value: bool) -> bool: ...
    @property
    def isImported(self) -> bool: ...
    @property
    def resolvedPath(self) -> str: ...
    @resolvedPath.setter
    def resolvedPath(self, value: str) -> str: ...
    @staticmethod
    def FindByPackage(packageName: str, packageVersion: str) -> IEnumerable_1[Sample]: ...
    def Import(self, options: Sample.ImportOptions = ...) -> bool: ...

    class ImportOptions(typing.SupportsInt):
        @typing.overload
        def __init__(self, value : int) -> None: ...
        @typing.overload
        def __init__(self, value : int, force_if_true: bool) -> None: ...
        def __int__(self) -> int: ...
        
        # Values:
        None_ : Sample.ImportOptions # 0
        OverridePreviousImports : Sample.ImportOptions # 1
        HideImportWindow : Sample.ImportOptions # 2



class Window(abc.ABC):
    @staticmethod
    def Open(packageToSelect: str) -> None: ...

