import typing
from UnityEngine.SocialPlatforms import ISocialPlatform, ILocalUser, IAchievement, ILeaderboard, IAchievementDescription, IUserProfile, IScore, TimeScope
from System import Action_1, Array_1

class GameCenterPlatform(ISocialPlatform):
    def __init__(self) -> None: ...
    @property
    def localUser(self) -> ILocalUser: ...
    def CreateAchievement(self) -> IAchievement: ...
    def CreateLeaderboard(self) -> ILeaderboard: ...
    def GetLoading(self, board: ILeaderboard) -> bool: ...
    def LoadAchievementDescriptions(self, callback: Action_1[Array_1[IAchievementDescription]]) -> None: ...
    def LoadAchievements(self, callback: Action_1[Array_1[IAchievement]]) -> None: ...
    def LoadUsers(self, userIds: Array_1[str], callback: Action_1[Array_1[IUserProfile]]) -> None: ...
    def ReportProgress(self, id: str, progress: float, callback: Action_1[bool]) -> None: ...
    def ReportScore(self, score: int, board: str, callback: Action_1[bool]) -> None: ...
    @staticmethod
    def ResetAllAchievements(callback: Action_1[bool]) -> None: ...
    def ShowAchievementsUI(self) -> None: ...
    @staticmethod
    def ShowDefaultAchievementCompletionBanner(value: bool) -> None: ...
    # Skipped LoadScores due to it being static, abstract and generic.

    LoadScores : LoadScores_MethodGroup
    class LoadScores_MethodGroup:
        @typing.overload
        def __call__(self, category: str, callback: Action_1[Array_1[IScore]]) -> None:...
        @typing.overload
        def __call__(self, board: ILeaderboard, callback: Action_1[bool]) -> None:...

    # Skipped ShowLeaderboardUI due to it being static, abstract and generic.

    ShowLeaderboardUI : ShowLeaderboardUI_MethodGroup
    class ShowLeaderboardUI_MethodGroup:
        @typing.overload
        def __call__(self) -> None:...
        @typing.overload
        def __call__(self, leaderboardID: str, timeScope: TimeScope) -> None:...


