
class ManagedDebugger:
    def __init__(self) -> None: ...
    @classmethod
    @property
    def isAttached(cls) -> bool: ...
    @classmethod
    @property
    def isEnabled(cls) -> bool: ...
    @staticmethod
    def Disconnect() -> None: ...

