
class Remote:
    def __init__(self) -> None: ...
    @classmethod
    @property
    def allowExitToHome(cls) -> bool: ...
    @classmethod
    @allowExitToHome.setter
    def allowExitToHome(cls, value: bool) -> bool: ...
    @classmethod
    @property
    def allowRemoteRotation(cls) -> bool: ...
    @classmethod
    @allowRemoteRotation.setter
    def allowRemoteRotation(cls, value: bool) -> bool: ...
    @classmethod
    @property
    def reportAbsoluteDpadValues(cls) -> bool: ...
    @classmethod
    @reportAbsoluteDpadValues.setter
    def reportAbsoluteDpadValues(cls, value: bool) -> bool: ...
    @classmethod
    @property
    def touchesEnabled(cls) -> bool: ...
    @classmethod
    @touchesEnabled.setter
    def touchesEnabled(cls, value: bool) -> bool: ...

