from UnityEngine import Vector4, Sprite, Vector2

class DataUtility:
    def __init__(self) -> None: ...
    @staticmethod
    def GetInnerUV(sprite: Sprite) -> Vector4: ...
    @staticmethod
    def GetMinSize(sprite: Sprite) -> Vector2: ...
    @staticmethod
    def GetOuterUV(sprite: Sprite) -> Vector4: ...
    @staticmethod
    def GetPadding(sprite: Sprite) -> Vector4: ...

