import typing
from System.Collections.Generic import IEqualityComparer_1

class FloatComparer(IEqualityComparer_1[float]):
    # Constructor .ctor(relative : Boolean) was skipped since it collides with above method
    @typing.overload
    def __init__(self) -> None: ...
    @typing.overload
    def __init__(self, error: float) -> None: ...
    @typing.overload
    def __init__(self, error: float, relative: bool) -> None: ...
    kEpsilon : float
    s_ComparerWithDefaultTolerance : FloatComparer
    @staticmethod
    def AreEqual(expected: float, actual: float, error: float) -> bool: ...
    @staticmethod
    def AreEqualRelative(expected: float, actual: float, error: float) -> bool: ...
    def Equals(self, a: float, b: float) -> bool: ...
    def GetHashCode(self, obj: float) -> int: ...

