import abc
from UnityEngine import RuntimePlatform

class AdvertisementSettings(abc.ABC):
    @classmethod
    @property
    def enabled(cls) -> bool: ...
    @classmethod
    @enabled.setter
    def enabled(cls, value: bool) -> bool: ...
    @classmethod
    @property
    def initializeOnStartup(cls) -> bool: ...
    @classmethod
    @initializeOnStartup.setter
    def initializeOnStartup(cls, value: bool) -> bool: ...
    @classmethod
    @property
    def testMode(cls) -> bool: ...
    @classmethod
    @testMode.setter
    def testMode(cls, value: bool) -> bool: ...
    @staticmethod
    def GetGameId(platform: RuntimePlatform) -> str: ...
    @staticmethod
    def GetPlatformGameId(platformName: str) -> str: ...
    @staticmethod
    def IsPlatformEnabled(platform: RuntimePlatform) -> bool: ...
    @staticmethod
    def SetGameId(platform: RuntimePlatform, gameId: str) -> None: ...
    @staticmethod
    def SetPlatformEnabled(platform: RuntimePlatform, value: bool) -> None: ...
    @staticmethod
    def SetPlatformGameId(platformName: str, gameId: str) -> None: ...

