import typing, abc
from UnityEditor.PackageManager import PackageCollection, Error, StatusCode, PackageInfo, PackOperationResult
from UnityEngine import ISerializationCallbackReceiver
from System import Array_1

class AddAndRemoveRequest(Request_1[PackageCollection]):
    @property
    def Error(self) -> Error: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Result(self) -> PackageCollection: ...
    @property
    def Status(self) -> StatusCode: ...


class AddRequest(Request_1[PackageInfo]):
    @property
    def Error(self) -> Error: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Result(self) -> PackageInfo: ...
    @property
    def Status(self) -> StatusCode: ...


class EmbedRequest(Request_1[PackageInfo]):
    @property
    def Error(self) -> Error: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Result(self) -> PackageInfo: ...
    @property
    def Status(self) -> StatusCode: ...


class ListRequest(Request_1[PackageCollection]):
    @property
    def Error(self) -> Error: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Result(self) -> PackageCollection: ...
    @property
    def Status(self) -> StatusCode: ...


class PackRequest(Request_1[PackOperationResult]):
    @property
    def Error(self) -> Error: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Result(self) -> PackOperationResult: ...
    @property
    def Status(self) -> StatusCode: ...


class RemoveRequest(Request_0):
    @property
    def Error(self) -> Error: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def PackageIdOrName(self) -> str: ...
    @property
    def Status(self) -> StatusCode: ...


class Request_GenericClasses(abc.ABCMeta):
    Generic_Request_GenericClasses_Request_1_T = typing.TypeVar('Generic_Request_GenericClasses_Request_1_T')
    def __getitem__(self, types : typing.Type[Generic_Request_GenericClasses_Request_1_T]) -> typing.Type[Request_1[Generic_Request_GenericClasses_Request_1_T]]: ...

class Request(Request_0, metaclass =Request_GenericClasses): ...

class Request_0(ISerializationCallbackReceiver, abc.ABC):
    @property
    def Error(self) -> Error: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Status(self) -> StatusCode: ...


Request_1_T = typing.TypeVar('Request_1_T')
class Request_1(typing.Generic[Request_1_T], Request_0):
    @property
    def Error(self) -> Error: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Result(self) -> Request_1_T: ...
    @property
    def Status(self) -> StatusCode: ...


class ResetToEditorDefaultsRequest(Request_0):
    @property
    def Error(self) -> Error: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def Status(self) -> StatusCode: ...


class SearchRequest(Request_1[Array_1[PackageInfo]]):
    @property
    def Error(self) -> Error: ...
    @property
    def IsCompleted(self) -> bool: ...
    @property
    def PackageIdOrName(self) -> str: ...
    @property
    def Result(self) -> Array_1[PackageInfo]: ...
    @property
    def Status(self) -> StatusCode: ...

