from UnityEngine import IntegratedSubsystem_1, IntegratedSubsystemDescriptor_1

class ExampleSubsystem(IntegratedSubsystem_1[ExampleSubsystemDescriptor]):
    def __init__(self) -> None: ...
    @property
    def running(self) -> bool: ...
    @property
    def subsystemDescriptor(self) -> ExampleSubsystemDescriptor: ...
    @property
    def SubsystemDescriptor(self) -> ExampleSubsystemDescriptor: ...
    def GetBool(self) -> bool: ...
    def PrintExample(self) -> None: ...


class ExampleSubsystemDescriptor(IntegratedSubsystemDescriptor_1[ExampleSubsystem]):
    def __init__(self) -> None: ...
    @property
    def disableBackbufferMSAA(self) -> bool: ...
    @property
    def id(self) -> str: ...
    @property
    def stereoscopicBackbuffer(self) -> bool: ...
    @property
    def supportsEditorMode(self) -> bool: ...
    @property
    def usePBufferEGL(self) -> bool: ...

