import abc
from UnityEngine import ScriptableObject, HideFlags

class EndNameEditAction(ScriptableObject, abc.ABC):
    @property
    def hideFlags(self) -> HideFlags: ...
    @hideFlags.setter
    def hideFlags(self, value: HideFlags) -> HideFlags: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, value: str) -> str: ...
    @abc.abstractmethod
    def Action(self, instanceId: int, pathName: str, resourceFile: str) -> None: ...
    def Cancelled(self, instanceId: int, pathName: str, resourceFile: str) -> None: ...
    def CleanUp(self) -> None: ...
    def OnEnable(self) -> None: ...

