import clr
from UnityEditor import IAudioEffectPlugin
from System import Array_1

class AudioMixerEffectPlugin(IAudioEffectPlugin):
    def __init__(self) -> None: ...
    def GetFloatBuffer(self, name: str, data: clr.Reference[Array_1[float]], numsamples: int) -> bool: ...
    def GetFloatParameter(self, name: str, value: clr.Reference[float]) -> bool: ...
    def GetFloatParameterInfo(self, name: str, minRange: clr.Reference[float], maxRange: clr.Reference[float], defaultValue: clr.Reference[float]) -> bool: ...
    def GetSampleRate(self) -> int: ...
    def IsPluginEditableAndEnabled(self) -> bool: ...
    def SetFloatParameter(self, name: str, value: float) -> bool: ...

